import json, os

out = r'D:\LvyzWeb\platform\src\content\crashai-expanded'

def save(course, fn):
    fp = os.path.join(out, fn)
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(course, f, ensure_ascii=False, indent=2)
    print('%s: %s (%d sections)' % (fn, course['slug'], len(course['sections'])))

# Course 14: SFT-RLHF
c14 = {
    "slug": "sft-rlhf",
    "title": "2.8 指令微调与RLHF",
    "description": "SFT/RLHF/PPO/DPO：让LLM从\u201C会说话\u201D到\u201C说好话\u201D",
    "category": "llm", "phase": "B", "order": 14,
    "sections": [
        {"type": "text", "title": "指令微调(SFT)：让模型学会听话", "content": "<p><b>预训练后的模型只会\u201C续写\u201D，不会\u201C听话\u201D。</b>如果你问预训练模型\u201C什么是量子力学？\u201D，它可能会继续写\u201C什么是量子力学？这是一个有趣的问题。在20世纪初，物理学家们发现...\u201D。它没有理解你是在问问题，需要回答。</p><p><b>SFT（Supervised Fine-Tuning）就是解决这个问题。</b>它用人工标注的\u201C指令-回答\u201D数据对模型进行微调。例如：</p><pre>输入：请解释量子力学\n输出：量子力学是研究微观粒子行为的物理学分支...\n输入：把这句话翻译成英文\n输出：Translation of this sentence...\n输入：写一首关于秋天的诗\n输出：秋风起，落叶黄...\u003c/pre><p><b>SFT数据量：</b>通常10万~100万条高质量指令对。数据质量比数量更重要。一条好的指令数据 = 清晰的指令 + 准确的回答 + 适当的格式。</p><p><b>SFT参数：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>学习率</td><td>微调步长</td><td>1e-5 ~ 5e-5</td><td>太大→破坏预训练知识；太小→微调无效</td></tr><tr><td>数据量</td><td>指令对数量</td><td>10K~100K</td><td>太少→过拟合；太多→训练成本增加</td></tr><tr><td>epoch数</td><td>完整遍历数据次数</td><td>1~3</td><td>太多→过拟合；太少→学习不充分</td></tr></table>"},
        {"type": "text", "title": "RLHF：用人类反馈让模型\u201C说人话\u201D", "content": "<p><b>SFT之后，模型能回答问题，但回答质量参差不齐。</b>有些回答太长、有些太短、有些语气不友好、有些甚至有偏见。RLHF（Reinforcement Learning from Human Feedback）用人类反馈来进一步调优模型。</p><p><b>RLHF三步流程：</b></p><p><b>Step 1: 训练奖励模型（Reward Model）</b>。让人类标注员对同一个问题的多个回答打分（1-5分）。例如：\u201C请解释黑洞\u201D的三个回答：回答A（5分，清晰准确）、回答B（3分，有部分错误）、回答C（1分，胡说八道）。用这些数据训练一个奖励模型，它能自动给回答打分。</p><p><b>Step 2: 用PPO强化学习训练策略模型。</b>策略模型生成回答，奖励模型打分，用PPO算法优化策略模型，让它生成高分回答。</p><p><b>Step 3: 迭代优化。</b>重复Step 2，每次用新的策略模型生成新回答，再用奖励模型打分，继续优化。</p><p><b>RLHF效果：</b>ChatGPT相比GPT-3，主要提升来自RLHF。RLHF让模型学会：回答要有帮助、不能有害、要诚实、语气要友好。</p>"},
        {"type": "formula", "title": "PPO vs DPO：两种RLHF算法", "content": "<p><b>PPO（Proximal Policy Optimization）</b>：OpenAI使用的RLHF算法。核心思想：限制每次更新的幅度，防止模型变化太大。</p><p><b>PPO目标函数：</b></p><pre>L^{PPO} = E[ min(r_t * A_t, clip(r_t, 1-ε, 1+ε) * A_t) ]\n其中：r_t = π_θ(a_t|s_t) / π_θ_old(a_t|s_t)（新策略 vs 旧策略的概率比）\nA_t = 优势函数（这个动作比平均水平好多少）\nε = 0.1~0.2（裁剪范围）</pre><p><b>PPO参数：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>ε (epsilon)</td><td>裁剪范围</td><td>0.1~0.2</td><td>太大→无约束；太小→更新太慢</td></tr><tr><td>KL散度系数</td><td>惩罚偏离SFT模型</td><td>0.01~0.1</td><td>太大→模型太保守；太小→偏离太多</td></tr><tr><td>学习率</td><td>策略模型学习率</td><td>1e-6~1e-5</td><td>太大→不稳定；太小→收敛慢</td></tr></table><p><b>DPO（Direct Preference Optimization）</b>：2023年提出的新算法，直接优化偏好，不需要奖励模型和PPO！</p><p><b>DPO优势：</b>更简单、更稳定、训练更快。DPO直接比较两个回答的偏好，让好的回答概率更高，差的回答概率更低。不需要训练奖励模型，也不需要复杂的PPO。</p><p><b>DPO vs PPO：</b></p><table border=\"1\"><tr><th>特性</th><th>PPO</th><th>DPO</th></tr><tr><td>需要奖励模型</td><td>是</td><td>否（直接优化偏好）</td></tr><tr><td>训练复杂度</td><td>高（需要Actor+Critic+Reward）</td><td>低（只需要策略模型）</td></tr><tr><td>稳定性</td><td>一般（超参数敏感）</td><td>好（更鲁棒）</td></tr><tr><td>效果</td><td>好（经过充分验证）</td><td>相当甚至更好</td></tr></table>"},
        {"type": "example", "title": "例子：RLHF数据标注流程", "content": "<p><b>场景：</b>标注员收到问题\u201C请解释机器学习\u201D，以及3个模型的回答。</p><p><b>回答A（5分）：</b>机器学习是人工智能的一个分支，它让计算机从数据中学习规律，而无需显式编程。例如：给计算机看1万张猫和狗的图片，它就能学会区分猫和狗。</p><p><b>回答B（3分）：</b>机器学习是一种技术。它使用算法来处理数据。有很多种算法。监督学习、无监督学习、强化学习。神经网络是其中一种。</p><p><b>回答C（1分）：</b>机器学习就是机器在学习。机器是人造的。学习很重要。我们要好好学习天天向上。</p><p><b>标注过程：</b></p><pre>1. 清晰性：A(5) > B(3) > C(1)\n2. 准确性：A(5) > B(3) > C(1)\n3. 有用性：A(5) > B(3) > C(1)\n总分：A(15) > B(9) > C(3)\n标注结果：A > B > C</pre><p><b>训练奖励模型：</b>用成千上万这样的标注对训练奖励模型。奖励模型学会预测：给定问题和回答，人类会打多少分。</p><p><b>PPO训练：</b>策略模型生成回答 → 奖励模型打分 → 如果分高，鼓励这个方向；如果分低，抑制这个方向。同时KL散度约束防止模型偏离SFT太远。</p>"},
        {"type": "exercise", "title": "练习：SFT与RLHF", "content": "<p><b>Q1：</b>SFT和预训练有什么区别？为什么SFT的学习率比预训练小10倍？</p><p><b>Q2：</b>RLHF的奖励模型训练目标是什么？它如何给回答打分？</p><p><b>Q3：</b>PPO的裁剪参数ε=0.2是什么意思？如果ε=0.5会怎样？</p><p><b>Q4：</b>DPO相比PPO的优势是什么？为什么DPO不需要奖励模型？</p><p><b>Q5：</b>SFT数据量10K和100K，哪个更好？如果10K是高质量人工标注，100K是低质量自动生成？</p>", "answer": "<p><b>A1：</b>预训练让模型学会语言规律（预测下一个词），SFT让模型学会遵循指令（根据指令生成回答）。SFT学习率小是因为预训练后的模型已经很好，微调时只需要小幅度调整，避免破坏已学到的知识。</p><p><b>A2：</b>奖励模型的训练目标是预测人类对回答的评分。输入=问题+回答，输出=分数（1-5）。训练数据来自人工标注的\u201C偏好对\u201D（同一个问题的多个回答，标注员排序）。</p><p><b>A3：</b>ε=0.2表示新策略和旧策略的概率比被限制在[0.8, 1.2]范围内。如果ε=0.5，范围变成[0.5, 1.5]，约束太弱，策略可能剧烈变化，导致训练不稳定。</p><p><b>A4：</b>DPO直接优化策略模型，让它对偏好的回答输出更高概率，对不喜欢的回答输出更低概率。不需要单独的奖励模型，因为DPO的优化目标本身就包含了偏好信息。更简单、更稳定、训练更快。</p><p><b>A5：</b>10K高质量人工标注更好。SFT数据质量比数量重要。10K高质量数据能让模型学会正确的回答格式、语气、内容。100K低质量数据可能引入错误和偏见，甚至导致模型性能下降。数据质量 > 数据数量。</p>"}
    ]
}
save(c14, 'course-14.json')

# Course 15: LLM Evaluation
c15 = {
    "slug": "llm-eval",
    "title": "2.9 LLM评估",
    "description": "Perplexity/BLEU/ROUGE/HumanEval：如何科学评价大语言模型",
    "category": "llm", "phase": "B", "order": 15,
    "sections": [
        {"type": "text", "title": "为什么评估很重要？——没有尺子的裁缝", "content": "<p><b>没有评估 = 没有方向。</b>就像裁缝没有尺子，无法知道衣服是否合身。训练模型时，如果没有科学的评估方法，你不知道模型是在进步还是在退步。</p><p><b>评估的三个维度：</b></p><p><b>1. 能力评估：</b>模型能做什么？（问答、翻译、代码、推理）</p><p><b>2. 安全评估：</b>模型不应该做什么？（生成有害内容、泄露隐私、产生偏见）</p><p><b>3. 效率评估：</b>模型的成本如何？（推理速度、内存占用、能耗）</p><p><b>常见评估指标：</b></p><table border=\"1\"><tr><th>指标</th><th>衡量什么</th><th>适用场景</th><th>优缺点</th></tr><tr><td>Perplexity</td><td>模型预测能力</td><td>预训练、语言建模</td><td>客观但只看概率，不评估质量</td></tr><tr><td>BLEU</td><td>生成文本与参考的匹配度</td><td>机器翻译、文本生成</td><td>快速自动评估，但不考虑语义</td></tr><tr><td>ROUGE</td><td>摘要与参考的重叠度</td><td>文本摘要</td><td>类似BLEU，关注召回率</td></tr><tr><td>HumanEval</td><td>代码生成正确率</td><td>代码能力</td><td>直接测试功能性，最真实</td></tr><tr><td>MMLU</td><td>多学科知识</td><td>通用知识</td><td>57个学科，全面但只是选择题</td></tr></table>"},
        {"type": "formula", "title": "Perplexity：模型的\u201C困惑程度\u201D", "content": "<p><b>Perplexity（PPL）是衡量语言模型预测能力的核心指标。</b></p><p><b>公式：</b></p><pre>PPL = exp( -(1/N) * Σ log P(wᵢ | w₁...wᵢ₋₁) ) = exp(L)\n其中：L = 平均交叉熵损失\nN = 词的总数</pre><p><b>直观理解：</b>PPL = 模型每次预测下一个词时，面临的等效选择数量。PPL=100意味着模型每次预测时，相当于从100个等概率词中猜。PPL=10意味着从10个词中猜。PPL越低越好。</p><p><b>类比：猜拳游戏。</b>如果我能100%猜中你出什么，PPL=1（没有选择）。如果我只能猜中10%，PPL=10（10个等概率选择）。如果完全随机猜，PPL=词汇表大小（几万个）。</p><p><b>数值例子：</b></p><pre>GPT-2 (1.5B参数): PPL ≈ 18.3 (WebText测试集)\nGPT-3 (175B参数): PPL ≈ 12.0\nGPT-4 (估计): PPL ≈ 8~10\n人类水平: PPL ≈ 5~8 (估计)</pre><p><b>PPL的局限性：</b>PPL只衡量预测能力，不衡量生成质量、安全性、有用性。一个PPL很低的模型可能生成有害内容或胡说八道。</p><p><b>参数说明：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>PPL</td><td>困惑度</td><td>8~20 (越好越小)</td><td>太大→预测能力差；太小→可能过拟合</td></tr><tr><td>测试集</td><td>评估用的数据</td><td>与训练集不同分布</td><td>同分布→过拟合；差距太大→评估不准</td></tr></table>"},
        {"type": "text", "title": "HumanEval与MMLU：直接测试能力", "content": "<p><b>HumanEval：代码能力的终极测试。</b>OpenAI 2021年发布。包含164个编程问题，每个问题有函数签名、文档字符串和若干测试用例。模型需要补全函数体，让测试用例全部通过。</p><p><b>HumanEval例子：</b></p><pre>def has_close_elements(numbers: List[float], threshold: float) -> bool:\n    \"\"\" Check if in given list of numbers, any two numbers are closer than given threshold.\"\"\"\n    # 模型需要补全这里\n    pass\n\n# 测试用例：\nassert has_close_elements([1.0, 2.0, 3.0], 0.5) == False\nassert has_close_elements([1.0, 2.0, 2.5], 0.6) == True\nassert has_close_elements([1.0, 2.0, 2.4], 0.5) == True\nassert has_close_elements([1.0, 2.0, 2.3], 0.3) == False\nassert has_close_elements([1.0, 2.0, 2.2], 0.2) == True\n\n# 正确补全：\nfor i in range(len(numbers)):\n    for j in range(i+1, len(numbers)):\n        if abs(numbers[i]-numbers[j]) < threshold:\n            return True\nreturn False</pre><p><b>HumanEval分数：</b></p><pre>GPT-3.5: 48.1%\nGPT-4: 67.0%\nGPT-4o: 90.2%\nClaude 3.5 Sonnet: 92.0%\n人类程序员: ~80-95%</pre><p><b>MMLU（Massive Multitask Language Understanding）：</b>加州大学伯克利分校发布。包含57个学科（数学、物理、化学、生物、历史、法律、计算机等），每个学科有多个选择题。测试模型的通用知识。</p><p><b>MMLU分数：</b></p><pre>GPT-3: 43.9%\nGPT-3.5: 70.0%\nGPT-4: 86.4%\n人类专家: 89.8%\nClaude 3 Opus: 86.8%</pre><p><b>其他重要基准：</b></p><table border=\"1\"><tr><th>基准</th><th>测试什么</th><th>代表模型分数</th></tr><tr><td>GSM8K</td><td>小学数学推理</td><td>GPT-4: 92.0%</td></tr><tr><td>HellaSwag</td><td>常识推理</td><td>GPT-4: 95.3%</td></tr><tr><td>TruthfulQA</td><td>回答真实性</td><td>GPT-4: 60.0% (仍有提升空间)</td></tr><tr><td>BBH</td><td>复杂推理</td><td>GPT-4: 83.1%</td></tr></table>"},
        {"type": "example", "title": "例子：计算BLEU分数", "content": "<p><b>场景：</b>机器翻译任务。参考翻译（人类翻译）和机器翻译结果如下。</p><p><b>参考翻译：</b>The cat is on the mat.</p><p><b>机器翻译A：</b>The cat is on the mat. (完美匹配)</p><p><b>机器翻译B：</b>There is a cat on the mat. (语义相同，用词不同)</p><p><b>机器翻译C：</b>The dog is under the table. (完全错误)</p><p><b>BLEU计算（简化版，只看1-gram）：</b></p><pre>参考的1-gram：The, cat, is, on, the, mat (6个)\n机器翻译A的1-gram：The, cat, is, on, the, mat (6个，全部匹配)\n机器翻译B的1-gram：There, is, a, cat, on, the, mat (7个，匹配：is, cat, on, the, mat = 5个)\n机器翻译C的1-gram：The, dog, is, under, the, table (6个，匹配：The, is, the = 3个)\n\nBLEU-A = 6/6 = 1.0 (100%)\nBLEU-B = 5/7 ≈ 0.71 (71%)\nBLEU-C = 3/6 = 0.5 (50%)\n\n加上长度惩罚（防止生成短句）：\n翻译A长度=6，参考长度=6，惩罚=1.0\n翻译B长度=7，参考长度=6，惩罚≈0.95\n翻译C长度=6，参考长度=6，惩罚=1.0\n\n最终BLEU:\nA: 1.0 * 1.0 = 1.0\nB: 0.71 * 0.95 ≈ 0.67\nC: 0.5 * 1.0 = 0.5</pre><p><b>结论：</b>BLEU-A最高（完美匹配），BLEU-B次之（语义正确但用词不同），BLEU-C最差（完全错误）。但注意：BLEU-B的语义其实和A一样，只是BLEU没考虑语义，只看词匹配。</p>"},
        {"type": "exercise", "title": "练习：LLM评估", "content": "<p><b>Q1：</b>PPL=20和PPL=5，哪个模型更好？如果PPL=1呢？</p><p><b>Q2：</b>BLEU分数高是否一定代表翻译质量好？为什么？</p><p><b>Q3：</b>HumanEval测试模型的什么能力？为什么它比PPL更能反映实际能力？</p><p><b>Q4：</b>MMLU包含57个学科，为什么用选择题而不是开放题？</p><p><b>Q5：</b>如果一个模型PPL很低但TruthfulQA分数也很低，说明什么问题？</p>", "answer": "<p><b>A1：</b>PPL=5更好。PPL越低表示模型预测能力越强。PPL=1意味着模型能100%预测正确（不可能，因为语言有歧义）。PPL=1可能是过拟合或测试集泄露。</p><p><b>A2：</b>不一定。BLEU只看词匹配，不考虑语义。例如\u201CThere is a cat on the mat\u201D和\u201CThe cat is on the mat\u201D语义相同，但BLEU可能不高。BLEU还受参考翻译数量影响（参考越多，BLEU越可靠）。</p><p><b>A3：</b>HumanEval测试代码生成能力。它直接运行测试用例，看代码是否能正确执行。PPL只衡量语言预测能力，一个PPL很低的模型可能完全不会写代码。HumanEval是功能性测试，最贴近实际应用。</p><p><b>A4：</b>选择题便于自动评估。开放题需要人工评判，成本高、主观性强、难以复现。选择题可以标准化评估，但局限性是只测试知识记忆，不测试创造性思维。</p><p><b>A5：</b>说明模型虽然预测能力强（PPL低），但可能生成不真实的内容（幻觉）。TruthfulQA低表示模型经常编造事实、错误信息。这揭示了仅优化PPL的局限性——模型需要同时优化真实性和有用性。</p>"}
    ]
}
save(c15, 'course-15.json')

print('\nDone with courses 14-15!')
