import json, os

out = r'D:\LvyzWeb\platform\src\content\crashai-expanded'

def save(course, fn):
    fp = os.path.join(out, fn)
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(course, f, ensure_ascii=False, indent=2)
    print('%s: %s (%d sections)' % (fn, course['slug'], len(course['sections'])))

# Course 12: LLM Training
c12 = {
    "slug": "llm-training",
    "title": "2.6 LLM训练",
    "description": "预训练全流程：数据清洗/Tokenization/训练策略/分布式训练",
    "category": "llm", "phase": "B", "order": 12,
    "sections": [
        {"type": "text", "title": "为什么需要预训练？——LLM的九年义务教育", "content": "<p><b>预训练是LLM的九年义务教育。</b>在模型学会回答问题之前，它必须先读遍天下书。</p><p><b>类比：学做饭。</b>你不可能在学会切菜、认识食材之前，直接做出米其林大餐。预训练就是让模型先通过阅读海量文本，学会语言的基本规律。</p><p><b>核心目标：预测下一个词。</b>当你读到今天天气很，你的大脑会猜出好、热、冷。预训练就是让模型在看了几千亿个词后，也能做这种预测。</p><p><b>数据规模：</b>GPT-3在约5000亿token上训练。如果把这比作读书，GPT-3读的书比全人类历史加起来还多。</p><p><b>自回归语言建模：</b>模型训练的目标是让P(第1个词) * P(第2个词|第1个词) * ... * P(第N个词|前面所有词)最大化。每个*表示并且。</p><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>参数数量(N)</td><td>模型权重总数</td><td>70B, 175B, 1.8T</td><td>太大→难训练；太小→表达能力弱</td></tr><tr><td>训练token数(D)</td><td>模型看到多少词</td><td>1T, 2T, 14T</td><td>太少→过拟合；太多→收益递减</td></tr><tr><td>学习率(lr)</td><td>每次参数调整步长</td><td>1e-4 ~ 3e-4</td><td>太大→发散；太小→收敛极慢</td></tr><tr><td>批次大小</td><td>每次更新看多少样本</td><td>4M tokens</td><td>太大→内存不够；太小→噪声大</td></tr><tr><td>上下文长度</td><td>模型一次能看多长</td><td>2048, 4096, 128K</td><td>太长→显存爆炸；太短→无法处理长文</td></tr></table>"},
        {"type": "text", "title": "数据清洗：质量比数量更重要", "content": "<p><b>Garbage In, Garbage Out。</b>用垃圾数据训练，模型就学会垃圾。1万亿高质量token可能比3万亿低质量token更好。</p><p><b>数据来源：</b>Common Crawl(网页)、书籍(Books3/Gutenberg)、学术论文(arXiv)、代码(GitHub)、维基百科。</p><p><b>关键步骤：</b>1.去重(MinHash算法，相似度>0.9→重复)；2.语言过滤(fastText识别176种语言)；3.质量过滤(困惑度过滤、删除重复行)；4.隐私过滤(删除身份证号、电话、邮箱)；5.毒性过滤(内容分类器打分>0.8→删除)。</p><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>重复阈值</td><td>MinHash相似度</td><td>0.80~0.95</td><td>太大→漏重复；太小→误删</td></tr><tr><td>困惑度阈值</td><td>低质量过滤线</td><td>参考模型平均2倍</td><td>太高→保留垃圾；太低→删除正常</td></tr><tr><td>毒性阈值</td><td>有害内容删除线</td><td>0.7~0.9</td><td>太高→保留有害；太低→删除正常</td></tr><tr><td>代码比例</td><td>代码占总数据比例</td><td>10%~30%</td><td>太高→像程序员说话；太低→编程弱</td></tr></table>"},
        {"type": "text", "title": "分布式训练：当模型太大一台GPU放不下", "content": "<p><b>为什么需要分布式训练？</b>以GPT-3(1750亿参数)为例，每个参数用4字节(FP32)，模型本身需要700GB内存。最强GPU(H100)只有80GB显存。一台绝对放不下。</p><p><b>类比：搬家。</b>3000斤的钢琴，你一个人搬不动，需要10个朋友(10台GPU)一起搬。</p><p><b>数据并行：</b>每台GPU保存完整模型副本。大batch分成小份，每台独立计算梯度，然后同步求平均。</p><p><b>模型并行：</b>1.张量并行：把矩阵切成几块放不同GPU。2.流水线并行：把模型按层拆分，数据像流水线流过。3.3D并行：三种并行同时使用，总GPU数=4*8=32块。</p><p><b>ZeRO：</b>DeepSpeed核心创新。分片存储优化器状态、梯度和参数。ZeRO-3配合CPU Offload，可以在消费级GPU训练百亿参数模型！</p><p><b>框架对比：</b>DeepSpeed(微软，超大规模)、Megatron-LM(NVIDIA，GPU集群)、FSDP(PyTorch原生)、Colossal-AI(潞晨，国产芯片)。</p>"},
        {"type": "formula", "title": "交叉熵损失", "content": "<p><b>预训练目标：让预测概率接近真实概率。</b></p><p><b>公式：</b>L = -(1/N) * Σᵢ log(P(yᵢ | y₁,...,yᵢ₋₁))</p><p><b>逐符号解释：</b></p><ul><li><b>L</b>：损失值，代表模型有多错。越大→越差；越小→越好。</li><li><b>-</b>：负号。log(概率)是负数，取负让结果变正。</li><li><b>1/N</b>：求平均。N是一句话的词数。</li><li><b>Σᵢ</b>：求和。对每个位置i计算损失后加起来。</li><li><b>log</b>：自然对数(以e为底)。</li><li><b>P(yᵢ | ...)</b>：在第i位置，模型给出正确词的概率。</li></ul><p><b>类比：猜谜游戏。</b>猜对概率0.01→log(0.01)≈-4.6→损失=4.6。猜对概率0.5→log(0.5)≈-0.69→损失=0.69。猜对概率0.99→log(0.99)≈-0.01→损失=0.01。</p><p><b>数值例子：</b>模型预测猫吃鱼，正确概率分别是0.5(猫)、0.7(吃)、0.9(鱼)。L = -(1/3)*[log(0.5)+log(0.7)+log(0.9)] = -(1/3)*[-0.693-0.357-0.105] = 0.385。</p><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>L</td><td>损失值</td><td>初期3~5，后期1.5~2.5</td><td>— 是训练结果</td></tr><tr><td>N</td><td>序列长度</td><td>512, 2048, 4096</td><td>太大→显存不足；太小→上下文不足</td></tr><tr><td>P(yᵢ)</td><td>正确词概率</td><td>后期0.3~0.5</td><td>不可能达1.0，但越接近越好</td></tr></table>"},
        {"type": "example", "title": "例子：数据并行中的梯度同步", "content": "<p><b>场景：</b>4块GPU，总batch=64，每块16个样本。模型只有一个权重w，初始值w=1.0。损失函数L(w)=(w-y)²。</p><p><b>前向传播：</b></p><pre>GPU1: y=2 → 损失=(1-2)²=1 → 梯度=2(1-2)=-2\nGPU2: y=3 → 损失=(1-3)²=4 → 梯度=2(1-3)=-4\nGPU3: y=4 → 损失=(1-4)²=9 → 梯度=2(1-4)=-6\nGPU4: y=5 → 损失=(1-5)²=16 → 梯度=2(1-5)=-8</pre><p><b>梯度同步：</b>总梯度=(-2)+(-4)+(-6)+(-8)=-20。平均梯度=-20/4=-5。</p><p><b>参数更新(学习率=0.1)：</b>w_new = 1.0 - 0.1*(-5) = 1.5。</p><p><b>验证：</b>4块GPU的结果和单块GPU处理全部数据完全相同。</p>"},
        {"type": "text", "title": "训练策略：Warmup、衰减与梯度裁剪", "content": "<p><b>1. Warmup(预热)：</b>训练开始时，模型参数随机初始化。此时大学习率会导致参数剧烈震荡。Warmup让学习率从0线性增加到目标值。Warmup步数=总步数的1%~5%。</p><p><b>2. 学习率衰减：</b>Linear Decay(线性下降到0，GPT-3使用)、Cosine Decay(余弦曲线，LLaMA使用)、Step Decay(每N步减半)。</p><p><b>3. 梯度裁剪：</b>如果梯度L2范数超过阈值，按比例缩小。公式：梯度 = 梯度 * (阈值 / ||梯度||)。典型阈值：1.0(GPT)~5.0。</p><p><b>4. 混合精度：</b>前向/反向用FP16(快且省内存)，参数更新用FP32(稳定)。维护FP32的主参数。</p><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>Warmup步数</td><td>从0到目标学习率的步数</td><td>总步数的1%~5%</td><td>太多→浪费时间；太少→不稳定</td></tr><tr><td>最大学习率</td><td>训练峰值学习率</td><td>1e-4~6e-4</td><td>太大→发散；太小→收敛极慢</td></tr><tr><td>梯度裁剪阈值</td><td>最大允许梯度范数</td><td>1.0~5.0</td><td>太大→无保护；太小→严重限制学习</td></tr></table>"},
        {"type": "exercise", "title": "练习：LLM训练", "content": "<p><b>Q1：</b>模型预测我爱中国，正确概率0.5(我)、0.7(爱)、0.9(中国)。计算交叉熵损失和困惑度。</p><p><b>Q2：</b>梯度向量[5,12,8]，阈值=10。计算裁剪后的梯度。方向是否改变？</p><p><b>Q3：</b>2块GPU，w=2.0，L(w)=(w-y)²，GPU1:y=1，GPU2:y=5，学习率=0.1。计算w更新结果。</p><p><b>Q4：</b>总训练10000步，Warmup=1000步，目标lr=0.001。第500步、1000步、5000步的学习率分别是？</p><p><b>Q5：</b>PPL=15和PPL=5，哪个模型更好？好多少？</p>", "answer": "<p><b>A1：</b>L=-(1/3)*[log(0.5)+log(0.7)+log(0.9)]=0.385。PPL=exp(0.385)≈1.47。</p><p><b>A2：</b>范数=√(25+144+64)=√233≈15.26>10。缩放=10/15.26≈0.655。裁剪后=[3.28,7.86,5.24]。方向不变(同比例缩放)。</p><p><b>A3：</b>GPU1梯度=2(2-1)=2。GPU2梯度=2(2-5)=-6。平均=-2。w_new=2.0-0.1*(-2)=2.2。</p><p><b>A4：</b>第500步:lr=(500/1000)*0.001=0.0005。第1000步:lr=0.001。第5000步:lr=0.001*(1-4000/9000)≈0.000556。</p><p><b>A5：</b>PPL=5更好。PPL越低越好。好15/5=3倍。信息论角度：log₂(15)≈3.9比特 vs log₂(5)≈2.3比特，减少1.6比特不确定性。</p>"}
    ]
}
save(c12, 'course-12.json')

# Course 13: Tokenizer
c13 = {
    "slug": "tokenizer",
    "title": "2.7 Tokenizer",
    "description": "BPE/WordPiece/Byte-level：文本如何变成数字——Tokenization原理与实战",
    "category": "llm", "phase": "B", "order": 13,
    "sections": [
        {"type": "text", "title": "Tokenizer是什么？——文本到数字的翻译官", "content": "<p><b>Tokenizer是LLM的翻译官。</b>它把人类能看懂的文字（你好世界），翻译成模型能处理的数字（[1, 45, 678, 23]）。没有Tokenizer，模型无法理解任何文字。</p><p><b>为什么要Tokenize？</b>神经网络只认识数字。它无法理解你好这两个字，但它能理解数字1和数字45。Tokenizer就是把文字映射到数字的桥梁。</p><p><b>Tokenization完整流程：</b>1.文本输入→2.分词（把文本切成小块）→3.映射到ID（每个token对应唯一整数）→4.输入模型（ID转换成向量）→5.输出解码（模型输出ID，再翻译回文字）。</p><p><b>为什么不用单个字符？</b>如果每个字符是一个token，英文26个字母，中文几万个汉字。但unhappiness有12个字符，如果是一个token，模型只需一步处理。而且词比字符更有语义。</p><p><b>为什么不用单个词？</b>英语有100万+单词，中文词更多。如果每个词是一个token，词汇表太大。而且新词不断出现（如bitcoin、ChatGPT），模型无法处理新词。</p><p><b>解决方案：子词（Subword）Tokenization。</b>把词拆成更小的、有意义的部分。例如：unhappiness → un + happiness。既减少了词汇表大小，又能处理新词（un + known = unknown）。</p><p><b>主流Tokenizer对比：</b></p><table border=\"1\"><tr><th>Tokenizer</th><th>算法</th><th>代表模型</th><th>特点</th></tr><tr><td>BPE</td><td>Byte Pair Encoding</td><td>GPT-2/3/4, LLaMA</td><td>合并最频繁的字符对，简单高效</td></tr><tr><td>WordPiece</td><td>贪婪子词分割</td><td>BERT</td><td>选择使语言模型概率最大的子词</td></tr><tr><td>SentencePiece</td><td>自监督学习</td><td>LLaMA, T5</td><td>不依赖语言，直接处理原始文本</td></tr><tr><td>Byte-level BPE</td><td>字节级BPE</td><td>GPT-2</td><td>用256个字节表示所有语言，词汇表极小</td></tr></table>"},
        {"type": "text", "title": "BPE算法：最聪明的合并游戏", "content": "<p><b>BPE（Byte Pair Encoding）是GPT系列使用的Tokenizer算法。</b>它的核心思想：反复合并文本中最频繁出现的字符对，直到词汇表达到目标大小。</p><p><b>BPE完整步骤（简单例子）：</b></p><p>假设训练语料只有4个单词（已拆分成字符）：low → l,o,w；lower → l,o,w,e,r；newest → n,e,w,e,s,t；widest → w,i,d,e,s,t。</p><p><b>初始词汇表：</b>所有字符 {l,o,w,e,r,n,s,t,i,d} = 10个token。</p><p><b>第1轮：找最频繁的字符对。</b>统计相邻字符对：l-o:2次，o-w:2次，w-e:2次（newest, widest），e-s:2次（newest, widest）。w-e和e-s并列最频繁（2次）。</p><p><b>合并we：</b>把w和e合并成新token we。词汇表=11个token。文本变成：low→l,o,w；lower→l,o,w,e,r；newest→n,we,s,t；widest→w,i,d,e,s,t。</p><p><b>第2轮：再找最频繁。</b>o-w:2次（low, lower）。合并ow：low→l,ow；lower→l,ow,e,r。</p><p><b>重复这个过程</b>，直到词汇表达到目标大小（如GPT-2的50,000）。</p><p><b>BPE的优雅之处：</b>频率驱动（常见组合如ing、er、tion自动合并为token）、处理新词（没见过ChatGPT？拆成Chat + GPT）、词汇表大小可控、多语言友好（Byte-level BPE用256个字节）。</p><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>vocab_size</td><td>最终词汇表大小</td><td>32K, 50K, 100K</td><td>太大→embedding层过大；太小→token序列过长</td></tr><tr><td>min_frequency</td><td>合并的最小频率</td><td>2</td><td>太大→错过常见组合；太小→合并噪声</td></tr><tr><td>special_tokens</td><td>特殊token</td><td>[CLS], [SEP], [MASK]</td><td>根据模型架构定制</td></tr></table>"},
        {"type": "text", "title": "中文Tokenizer的特殊挑战", "content": "<p><b>中文没有空格，这是最大的挑战。</b>英文Hello world天然有空格分词，中文你好世界没有空格。中文Tokenizer必须自己决定切分位置。</p><p><b>中文Tokenizer的三种策略：</b></p><p><b>1. 字符级：</b>每个汉字是一个token。优点：词汇表小（几千个常用汉字），不会遇到未登录词。缺点：序列太长。今天天气很好=7个token，但语义上只有3-4个概念。</p><p><b>2. 词级：</b>用分词工具（如jieba）先切词，每个词是一个token。优点：语义完整。今天天气很好=3个token（今天/天气/很好）。缺点：词汇表巨大（几十万个词），新词OOV严重。</p><p><b>3. 子词级：BPE在中文中的表现。</b>BPE能发现有意义的组合：快乐→快+乐（BPE可能合并为快乐，因为这对很常见）；不快乐→不+快乐；超级快乐→超级+快乐。</p><p><b>中文Tokenizer实践建议：</b></p><table border=\"1\"><tr><th>Tokenizer</th><th>适用场景</th><th>中文表现</th></tr><tr><td>BERT-wwm</td><td>中文NLP任务</td><td>Whole Word Masking，整词掩码</td></tr><tr><td>ChatGLM-Tokenizer</td><td>中文对话</td><td>针对中文优化，中英文混合效果好</td></tr><tr><td>SentencePiece</td><td>多语言模型</td><td>不依赖空格，中文/英文/日文统一处理</td></tr><tr><td>Qwen-Tokenizer</td><td>中文大模型</td><td>针对中文词汇表优化，扩展性好</td></tr></table>"},
        {"type": "code", "title": "代码实战：用HuggingFace训练自己的Tokenizer", "content": "<p>我们用HuggingFace的tokenizers库来训练一个BPE tokenizer。</p><pre>from tokenizers import Tokenizer\nfrom tokenizers.models import BPE\nfrom tokenizers.trainers import BpeTrainer\nfrom tokenizers.pre_tokenizers import Whitespace\n\n# 1. 创建BPE模型\ntokenizer = Tokenizer(BPE(unk_token='[UNK]'))\n\n# 2. 设置预分词器（先用空格切分）\ntokenizer.pre_tokenizer = Whitespace()\n\n# 3. 创建训练器\ntrainer = BpeTrainer(\n    vocab_size=50000,        # 目标词汇表大小\n    min_frequency=2,          # 最少出现2次才合并\n    special_tokens=['[PAD]', '[UNK]', '[CLS]', '[SEP]', '[MASK]']\n)\n\n# 4. 训练（从文本文件）\nfiles = ['train.txt']  # 你的训练语料\ntokenizer.train(files, trainer)\n\n# 5. 保存\ntokenizer.save('my_bpe_tokenizer.json')\n\n# 6. 使用\noutput = tokenizer.encode('Hello world!')\nprint(output.tokens)   # ['Hello', ' world', '!']\nprint(output.ids)      # [1, 45, 23]\nprint(tokenizer.decode(output.ids))  # Hello world!</pre><p><b>参数详解：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>vocab_size</td><td>目标词汇表大小</td><td>32K-100K</td><td>太大→模型参数过多；太小→序列过长</td></tr><tr><td>min_frequency</td><td>合并的最小频率</td><td>2</td><td>太大→错过常见组合；太小→合并噪声</td></tr><tr><td>unk_token</td><td>未知词标记</td><td>[UNK]</td><td>— 必须存在</td></tr><tr><td>special_tokens</td><td>特殊token列表</td><td>[PAD],[UNK],[CLS],[SEP],[MASK]</td><td>根据模型需求定制</td></tr></table>"},
        {"type": "example", "title": "例子：对比不同Tokenizer的编码结果", "content": "<p><b>原文：unhappiness</b></p><p><b>字符级：</b>u,n,h,a,p,p,i,n,e,s,s = 11个token</p><p><b>词级：</b>unhappiness = 1个token（如果在词汇表里）</p><p><b>BPE（GPT-2风格）：</b>un + happiness = 2个token（如果un和happiness都是常见子词）；或un + happy + ness = 3个token（如果happy更常见）</p><p><b>结论：</b>子词级Tokenizer在词汇表大小和序列长度之间取得了最佳平衡。BPE能自动发现最有价值的子词组合。</p><p><b>另一个例子：中文</b></p><p><b>原文：</b>人工智能技术</p><p><b>字符级：</b>人,工,智,能,技,术 = 6个token</p><p><b>词级（jieba）：</b>人工智能, 技术 = 2个token</p><p><b>BPE（中文优化）：</b>人工 + 智能 + 技术 = 3个token（如果这三个子词常见）；或人工 + 智 + 能 + 技 + 术 = 5个token（如果智能未被合并）</p><p>这取决于训练语料中哪些子词组合最常见。</p>"},
        {"type": "exercise", "title": "练习：Tokenizer", "content": "<p><b>Q1：</b>为什么英文用空格分词，但中文用空格分词效果差？</p><p><b>Q2：</b>BPE的核心思想是什么？为什么它能处理新词？</p><p><b>Q3：</b>假设BPE训练语料中chat出现100次，bot出现50次，chatbot出现30次。如果词汇表已满，BPE会合并哪个对？</p><p><b>Q4：</b>中文Tokenizer用字符级有什么优缺点？用词级有什么优缺点？</p><p><b>Q5：</b>vocab_size=10000和vocab_size=100000分别对模型有什么影响？</p>", "answer": "<p><b>A1：</b>英文是拼音文字，空格天然分隔单词。中文是意音文字，没有空格，每个字独立但组合成词才有完整含义。人工智能分开意义不同，人工智能组合才有完整含义。</p><p><b>A2：</b>BPE的核心思想是反复合并语料中最频繁出现的字符对，形成子词。它能处理新词因为新词可以拆成已知的子词。例如ChatGPT未见过，但可以拆成Chat + GPT（如果这两个子词在词汇表中）。</p><p><b>A3：</b>BPE会合并出现最频繁的字符对。chat(100) + bot(50) = 需要看相邻对。chatbot中的chat和bot相邻出现30次。如果ch和at等子词更频繁，会先合并它们。具体取决于整个语料的频率分布。</p><p><b>A4：</b>字符级：优点→词汇表小（几千字），不会OOV；缺点→序列长，语义碎片化。词级：优点→语义完整；缺点→词汇表大（几十万个词），新词OOV严重。</p><p><b>A5：</b>vocab_size=10000：embedding层小，但每个token代表的语义信息少，序列长（一篇长文可能需要1000+token）。vocab_size=100000：embedding层大（增加模型参数），但每个token更语义化，序列短。需要平衡：通常32K-50K是最佳点。</p>"}
    ]
}
save(c13, 'course-13.json')

print('\nDone with courses 12-13!')
