import json, os

out = r'D:\LvyzWeb\platform\src\content\crashai-expanded'

def save(course, fn):
    fp = os.path.join(out, fn)
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(course, f, ensure_ascii=False, indent=2)
    print('%s: %s (%d sections)' % (fn, course['slug'], len(course['sections'])))

# Course 23: Frontier
c23 = {
    "slug": "frontier",
    "title": "3.7 前沿探索",
    "description": "MoE/长上下文/世界模型/具身智能：AI的下一个前沿",
    "category": "llm", "phase": "C", "order": 23,
    "sections": [
        {"type": "text", "title": "Mixture of Experts (MoE)：用大模型的智能，花小模型的钱", "content": "<p><b>MoE（混合专家模型）是2024年最热门的模型架构。</b>GPT-4、Mixtral 8x7B、DeepSeek-V2都用了MoE。核心思想：不是所有参数都参与每次计算，只激活一部分专家。</p><p><b>类比：医院会诊。</b>一个病人来了，不需要全院1000个医生都看。只需要根据症状，激活3-5个相关科室的专家。 MoE就像这样：每次输入，只路由到最相关的几个专家网络。</p><p><b>MoE架构：</b></p><pre>输入 → 路由器(Router) → 选择Top-k专家 → 专家网络(Expert) → 加权聚合 → 输出\n\n路由器：一个小网络，决定激活哪些专家\n专家网络：多个并行的FFN（前馈网络），每个处理不同方面\nTop-k：通常k=2，每次只激活2个专家（如8个专家中选2个）\n</pre><p><b>参数效率：</b></p><pre>Mixtral 8x7B：\n- 总参数量：46.7B（8个专家，每个7B）\n- 激活参数量：12.9B（每次只激活2个专家）\n- 性能：接近70B密集模型\n- 推理速度：比70B模型快得多（因为只计算12.9B参数）</pre><p><b>MoE的优势与挑战：</b></p><table border=\"1\"><tr><th>特性</th><th>优势</th><th>挑战</th></tr><tr><td>参数效率</td><td>总参数多，激活少</td><td>内存仍需存储所有参数</td></tr><tr><td>推理速度</td><td>比同性能密集模型快</td><td>专家切换有开销</td></tr><tr><td>专业化</td><td>不同专家学不同领域</td><td>负载均衡难</td></tr><tr><td>扩展性</td><td>增加专家几乎线性提升</td><td>通信开销增加</td></tr></table><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>num_experts</td><td>专家数量</td><td>8~64</td><td>太多→路由难；太少→不专业</td></tr><tr><td>top_k</td><td>每次激活专家数</td><td>2~4</td><td>太多→效率低；太少→信息丢失</td></tr><tr><td>capacity_factor</td><td>容量因子</td><td>1.0~1.5</td><td>太高→浪费；太低→丢弃token</td></tr></table>"},
        {"type": "text", "title": "长上下文：从4K到1M的突破", "content": "<p><b>上下文长度是LLM最重要的能力之一。</b>4K上下文能读一篇论文，128K能读一本书，1M能读一个代码库。</p><p><b>上下文长度演进：</b></p><pre>GPT-3 (2020): 2,048 tokens\nGPT-3.5 (2022): 4,096 tokens\nGPT-4 (2023): 8,192 / 32,768 tokens\nClaude 2.1 (2023): 200,000 tokens\nGemini 1.5 Pro (2024): 1,000,000 tokens (1M!)\nClaude 3 Opus (2024): 200,000 tokens\nKimi (2024): 200,000 tokens\n</pre><p><b>为什么长上下文难？</b></p><p><b>1. 计算复杂度：</b>Attention机制的复杂度是O(N²)，N=token数。4K上下文 = 1600万次计算，1M上下文 = 1万亿次计算（62500倍！）。</p><p><b>2. 内存占用：</b>1M上下文，每个token存KV Cache。假设d=4096，FP16：1M × 4096 × 2字节 × 2(K+V) = 16.4GB。仅KV Cache就16GB！</p><p><b>3. 注意力稀释：</b>序列太长，注意力分数被稀释，远处的token难以关注到。</p><p><b>长上下文解决方案：</b></p><ul><li><b>稀疏注意力：</b>只计算部分位置的注意力。如：局部注意力（只看附近token）、滑动窗口（看左右各W个token）、Longformer（组合局部+全局注意力）</li><li><b>线性注意力：</b>把O(N²)降到O(N)。如：Linear Attention、Performer、RWKV。</li><li><b>外推（Extrapolation）：</b>在短上下文训练，用技术扩展到长上下文。如：ALiBi（位置编码）、RoPE扩展（位置插值）、NTK-aware扩展。</li><li><b>Ring Attention：</b>把长序列分成多个块，在多个GPU上并行计算注意力。</li><li><b>内存优化：</b>KV Cache压缩（量化、剪枝）、FlashAttention（IO感知优化）。</li></ul><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>context_length</td><td>最大上下文长度</td><td>4K~1M</td><td>太长→计算爆炸；太短→信息不足</td></tr><tr><td>sliding_window</td><td>滑动窗口大小</td><td>512~4096</td><td>太大→不稀疏；太小→丢失远处信息</td></tr><tr><td>global_tokens</td><td>全局注意力token数</td><td>16~128</td><td>太少→全局信息不足</td></tr></table>"},
        {"type": "text", "title": "世界模型与具身智能：AI理解物理世界", "content": "<p><b>世界模型（World Model）：</b>AI学习理解物理世界的规律。知道重力让物体下落，知道水往低处流，知道球会反弹。这是通用人工智能(AGI)的关键。</p><p><b>类比：婴儿的学习。</b>婴儿通过观察世界、互动、试错，建立对物理世界的直觉。世界模型就是AI的\u201C直觉物理\u201D。</p><p><b>世界模型代表工作：</b></p><ul><li><b>Sora (OpenAI, 2024)：</b>视频生成模型，但展现出对物理世界的理解（物体 permanence、碰撞、流体）。</li><li><b>GAIA-1 (Wayve, 2023)：</b>自动驾驶世界模型，能预测未来交通场景。</li><li><b>Genie (Google DeepMind, 2024)：</b>从视频训练世界模型，可以控制虚拟环境。</li><li><b>JEPA (LeCun, 2023)：</b>联合嵌入预测架构，通过预测世界来学习。</li></ul><p><b>具身智能（Embodied AI）：</b>AI有身体，能在物理世界中行动。不是只存在于服务器里，而是有机器人身体，能感知、行动、学习。</p><p><b>具身智能的挑战：</b></p><pre>1. 感知：摄像头、触觉、力觉 → 多模态融合\n2. 行动：精确控制机械臂、行走、抓取\n3. 安全：不能伤害人类、不能破坏环境\n4. 泛化：在实验室训练的模型，能否在真实家庭工作？\n5. 实时：机器人需要毫秒级响应，但LLM推理需要秒级\n</pre><p><b>具身智能代表：</b></p><table border=\"1\"><tr><th>系统</th><th>公司</th><th>特点</th></tr><tr><td>Figure 01</td><td>Figure AI</td><td>人形机器人，OpenAI合作</td></tr><tr><td>Optimus (擎天柱)</td><td>Tesla</td><td>工厂场景，大规模量产计划</td></tr><tr><td>Atlas</td><td>Boston Dynamics</td><td>极致运动能力，液压驱动</td></tr><tr><td>RT-2</td><td>Google DeepMind</td><td>视觉-语言-动作端到端</td></tr></table><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>observation_freq</td><td>感知频率</td><td>30~60Hz</td><td>太低→反应慢；太高→计算压力大</td></tr><tr><td>action_dim</td><td>动作空间维度</td><td>7~50</td><td>太少→不够灵活；太多→难学习</td></tr><tr><td>sim2real_gap</td><td>仿真到现实差距</td><td>越小越好</td><td>太大→仿真训练无效</td></tr></table>"},
        {"type": "exercise", "title": "练习：前沿探索", "content": "<p><b>Q1：</b>MoE相比密集模型，核心优势是什么？为什么说MoE\u201C用大模型的智能，花小模型的钱\u201D？</p><p><b>Q2：</b>Attention复杂度是O(N²)。如果上下文从4K扩展到1M，计算量增加了多少倍？为什么长上下文这么难？</p><p><b>Q3：</b>世界模型和具身智能有什么关系？为什么LeCun认为世界模型是通往AGI的关键？</p><p><b>Q4：</b>MoE的负载均衡问题是什么？如果所有token都路由到同一个专家，会怎样？</p><p><b>Q5：</b>设计一个MoE架构：8个专家，每个7B参数，top_k=2。计算总参数量、激活参数量、推理时计算量相对于70B密集模型的比例。</p>", "answer": "<p><b>A1：</b>MoE核心优势：1.参数效率高——总参数多（如46.7B），但每次只激活少量（如12.9B），性能接近70B密集模型；2.推理速度快——因为计算量小；3.专业化——不同专家学不同领域。\u201C用大模型的智能，花小模型的钱\u201D：训练时用大数据训大模型，推理时只计算小模型大小的参数。</p><p><b>A2：</b>4K=4000, 1M=1,000,000。计算量增加=(1M/4K)²=(250)²=62,500倍。长上下文难因为：1.计算量爆炸；2.内存占用巨大（KV Cache）；3.注意力稀释（远处token难以关注）。</p><p><b>A3：</b>世界模型是AI理解物理世界的规律，具身智能是AI有身体在物理世界中行动。两者关系：具身智能需要世界模型来理解环境，世界模型可以通过具身交互来学习和验证。LeCun认为人类智能的核心是世界模型——我们时刻在预测世界的状态，规划行动。纯语言模型缺少这种\u201C物理直觉\u201D。</p><p><b>A4：</b>负载均衡问题：如果所有token都路由到同一个专家，其他专家不被训练，浪费参数。解决方案：1.辅助损失函数（auxiliary loss）鼓励均匀分布；2.容量限制（capacity factor）每个专家最多处理一定数量的token；3.噪声注入（Noisy Top-k）给路由分数加噪声。</p><p><b>A5：</b>总参数量=8×7B=56B（加上路由器等，约46.7B，如Mixtral）。激活参数量=2×7B=14B（加上共享参数，约12.9B）。推理计算量≈14B/70B=20%。即MoE推理只需密集模型20%的计算量，但性能接近。</p>"}
    ]
}
save(c23, 'course-23.json')

# Course 24: CrashAI Resources
c24 = {
    "slug": "crashai-resources",
    "title": "3.8 资源汇总",
    "description": "学习路径、论文、工具、社区：CrashAI课程资源导航",
    "category": "llm", "phase": "C", "order": 24,
    "sections": [
        {"type": "text", "title": "CrashAI学习路径总览", "content": "<p><b>CrashAI课程设计为从0到1的完整学习路径。</b>3个阶段，25个课程，从Python基础到前沿探索。</p><p><b>阶段A：基础（0-6课）</b></p><pre>00 高数唤醒：导数、偏导、梯度、链式法则、矩阵、概率\n01 Python速成：语法、NumPy、函数、类\n02 优化器：BGD/SGD/Momentum/AdaGrad/RMSprop/Adam\n03 激活函数：Sigmoid/ReLU/LeakyReLU/GELU/Swish/Softmax\n04 损失函数：MSE/MAE/CE/BCE/Focal/Huber\n05 训练技巧：Dropout/L2/BatchNorm/梯度裁剪/Warmup\n06 数据预处理：归一化/标准化/编码/增强/清洗\n</pre><p><b>阶段B：核心（7-16课）</b></p><pre>07 Transformer：Self-Attention/Multi-Head/Position Encoding\n08 Pandas：DataFrame/Series/清洗/聚合/分组/可视化\n09 Scikit-learn：分类/回归/GBDT/SHAP\n10 RAG基础：LangChain/Chroma/VectorDB/检索策略\n11 GPT系列：GPT-1→2→3→4/参数扩展/数据增长\n12 LLM训练：预训练/数据清洗/Tokenization/分布式训练\n13 Tokenizer：BPE/WordPiece/Byte-level\n14 指令微调与RLHF：SFT/PPO/DPO/奖励模型\n15 LLM评估：PPL/BLEU/ROUGE/HumanEval/MMLU\n16 AIGC：扩散模型/Stable Diffusion/LoRA/多模态\n</pre><p><b>阶段C：应用（17-24课）</b></p><pre>17 Agent：ReAct/Tool/Planning/Memory\n18 多Agent协作：Multi-Agent/通信/工作流编排\n19 RAG高级：混合检索/重排序/查询分解\n20 多模态处理：PDF/Word/Excel/图片/音频/视频\n21 工程整合：API设计/缓存/监控/日志/测试/部署\n22 MLOps：模型管理/CI-CD/监控/A-B测试\n23 前沿探索：MoE/长上下文/世界模型/具身智能\n24 资源汇总：学习路径/论文/工具/社区（本课）\n</pre>"},
        {"type": "text", "title": "推荐论文（按学习顺序）", "content": "<p><b>基础论文：</b></p><table border=\"1\"><tr><th>论文</th><th>年份</th><th>核心贡献</th></tr><tr><td>Adam: A Method for Stochastic Optimization</td><td>2014</td><td>Adam优化器，最广泛使用的优化算法</td></tr><tr><td>Batch Normalization</td><td>2015</td><td>BN层，加速训练</td></tr><tr><td>Dropout: A Simple Way to Prevent Overfitting</td><td>2014</td><td>Dropout正则化</td></tr></table><p><b>核心论文：</b></p><table border=\"1\"><tr><th>论文</th><th>年份</th><th>核心贡献</th></tr><tr><td>Attention Is All You Need (Transformer)</td><td>2017</td><td>Self-Attention，现代AI基石</td></tr><tr><td>BERT: Pre-training of Deep Bidirectional Transformers</td><td>2018</td><td>双向预训练，NLP里程碑</td></tr><tr><td>GPT-1: Improving Language Understanding by Generative Pre-Training</td><td>2018</td><td>生成式预训练</td></tr><tr><td>GPT-2: Language Models are Unsupervised Multitask Learners</td><td>2019</td><td>零样本学习，WebText</td></tr><tr><td>GPT-3: Language Models are Few-Shot Learners</td><td>2020</td><td>1750亿参数，上下文学习</td></tr><tr><td>Training language models to follow instructions with human feedback (InstructGPT)</td><td>2022</td><td>RLHF，SFT，PPO</td></tr></table><p><b>应用与前沿论文：</b></p><table border=\"1\"><tr><th>论文</th><th>年份</th><th>核心贡献</th></tr><tr><td>LoRA: Low-Rank Adaptation of Large Language Models</td><td>2021</td><td>参数高效微调</td></tr><tr><td>Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks</td><td>2020</td><td>RAG基础</td></tr><tr><td>ReAct: Synergizing Reasoning and Acting in Language Models</td><td>2022</td><td>Agent推理-行动</td></tr><tr><td>DPO: Direct Preference Optimization</td><td>2023</td><td>无需奖励模型的RLHF</td></tr><tr><td>Mixtral of Experts</td><td>2023</td><td>开源MoE模型</td></tr><tr><td>World Models</td><td>2018</td><td>Ha, Schmidhuber，世界模型</td></tr></table>"},
        {"type": "text", "title": "推荐工具与框架", "content": "<p><b>深度学习框架：</b></p><table border=\"1\"><tr><th>工具</th><th>用途</th><th>特点</th></tr><tr><td>PyTorch</td><td>深度学习</td><td>动态图，易调试，学术界首选</td></tr><tr><td>TensorFlow</td><td>深度学习</td><td>静态图，生产部署强</td></tr><tr><td>JAX</td><td>深度学习</td><td>Google出品，函数式，自动并行</td></tr><tr><td>HuggingFace Transformers</td><td>预训练模型</td><td>最大的开源模型库</td></tr></table><p><b>LLM应用框架：</b></p><table border=\"1\"><tr><th>工具</th><th>用途</th><th>特点</th></tr><tr><td>LangChain</td><td>LLM应用</td><td>模块化，Chain抽象，工具集成</td></tr><tr><td>LlamaIndex</td><td>RAG</td><td>数据索引，检索优化</td></tr><tr><td>AutoGPT</td><td>Agent</td><td>自主Agent，目标驱动</td></tr><tr><td>MetaGPT</td><td>多Agent</td><td>多Agent软件开发</td></tr></table><p><b>模型训练与部署：</b></p><table border=\"1\"><tr><th>工具</th><th>用途</th><th>特点</th></tr><tr><td>DeepSpeed</td><td>分布式训练</td><td>ZeRO优化，微软出品</td></tr><tr><td>vLLM</td><td>推理加速</td><td>PagedAttention，高吞吐</td></tr><tr><td>Text Generation Inference</td><td>推理服务</td><td>HuggingFace出品，易部署</td></tr><tr><td>MLflow</td><td>实验管理</td><td>实验追踪，模型注册</td></tr></table><p><b>数据与评估：</b></p><table border=\"1\"><tr><th>工具</th><th>用途</th><th>特点</th></tr><tr><td>Weights & Biases</td><td>实验可视化</td><td> beautiful charts，团队协作</td></tr><tr><td>TensorBoard</td><td>训练可视化</td><td>TensorFlow配套，轻量</td></tr><tr><td>EleutherAI LM Eval</td><td>模型评估</td><td>标准化评估框架</td></tr><tr><td>Cleanlab</td><td>数据清洗</td><td>自动检测错误标签</td></tr></table>"},
        {"type": "text", "title": "学习社区与资源", "content": "<p><b>推荐社区：</b></p><ul><li><b>HuggingFace (huggingface.co)：</b>最大的开源AI社区。模型、数据集、Spaces（应用展示）。</li><li><b>Papers With Code (paperswithcode.com)：</b>论文+代码实现，追踪SOTA。</li><li><b>Reddit r/MachineLearning：</b>最新讨论，研究者交流。</li><li><b>GitHub Awesome-LLM：</b>LLM资源汇总，持续更新。</li><li><b>中文社区：知乎AI话题、机器之心、PaperWeekly。</b></li></ul><p><b>推荐课程（补充）：</b></p><ul><li><b>Stanford CS224N：</b>NLP with Deep Learning，Transformer讲解最清晰。</li><li><b>Stanford CS231N：</b>Convolutional Neural Networks for Visual Recognition，计算机视觉基础。</li><li><b>Fast.ai：</b>Practical Deep Learning for Coders，实用导向。</li><li><b>3Blue1Brown：</b>神经网络/线性代数/微积分的可视化解释（YouTube）。</li><li><b>李沐《动手学深度学习》：</b>免费中文教材+视频，动手实践。</li></ul><p><b>CrashAI下一步：</b></p><pre>1. 完成所有25课的练习（至少做50%）\n2. 选择一个方向深入：\n   - 研究：读论文，复现模型，投稿会议\n   - 工程：做项目，开源贡献，找工作\n   - 产品：做应用，创业，解决实际问题\n3. 加入社区：参与开源项目，回答问题，写博客\n4. 持续学习：AI发展极快，每周都有新论文\n</pre>"},
        {"type": "exercise", "title": "练习：资源汇总", "content": "<p><b>Q1：</b>根据CrashAI的学习路径，如果你已经学完阶段A和B，接下来应该优先学什么？为什么？</p><p><b>Q2：</b>PyTorch和TensorFlow各有什么特点？如果你要做研究，选哪个？如果你要做生产部署，选哪个？</p><p><b>Q3：</b>为什么HuggingFace Transformers是LLM入门最重要的工具？它解决了什么问题？</p><p><b>Q4：</b>找到5篇核心论文，按年份排序。你能看出LLM发展的什么趋势？</p><p><b>Q5：</b>设计一个你自己的AI学习计划。你想成为研究员、工程师还是产品经理？需要侧重哪些课程？</p>", "answer": "<p><b>A1：</b>接下来应该优先学阶段C的应用课程（17-22课）。因为阶段A和B建立了理论基础，阶段C教你如何把理论应用到实际问题：Agent、RAG、多模态、工程部署、MLOps。这些是企业最需要的实战技能。</p><p><b>A2：</b>PyTorch：动态图，调试方便，API直观，学术界首选。TensorFlow：静态图，生产部署优化好，TFX生态完整。研究选PyTorch（迭代快，社区活跃）。生产部署选TensorFlow（TFX、TensorRT优化、企业支持）。</p><p><b>A3：</b>HuggingFace Transformers提供了统一的模型加载、使用、微调接口。它解决了：1.模型下载和格式统一（不用每个模型写不同代码）；2.预训练权重获取（下载即用）；3.Tokenizer配套（模型和Tokenizer绑定）；4.微调框架（Trainer）；5.社区生态（模型共享、数据集、Spaces）。</p><p><b>A4：</b>核心论文排序：2017 Transformer → 2018 BERT/GPT-1 → 2019 GPT-2 → 2020 GPT-3/RAG → 2021 LoRA → 2022 InstructGPT/RLHF/ReAct → 2023 DPO/MoE。趋势：1.模型越来越大（1.17亿→1750亿）；2.从预训练到对齐（SFT/RLHF）；3.从单模态到多模态；4.从通用到专用（RAG/Agent）；5.从训练到高效微调（LoRA/MoE）。</p><p><b>A5：</b>研究员：侧重阶段B（Transformer、LLM训练、RLHF、评估），多读论文，做实验。工程师：侧重阶段C（Agent、RAG、工程部署、MLOps），多做项目。产品经理：侧重17-20课（Agent、RAG、多模态），了解能力边界，设计产品。</p>"}
    ]
}
save(c24, 'course-24.json')

print('\nAll 25 courses (0-24) generated successfully!')
