import json, os

out = r'D:\LvyzWeb\platform\src\content\crashai-expanded'

def save(course, fn):
    fp = os.path.join(out, fn)
    with open(fp, 'w', encoding='utf-8') as f:
        json.dump(course, f, ensure_ascii=False, indent=2)
    print('%s: %s (%d sections)' % (fn, course['slug'], len(course['sections'])))

# Course 20: Multi-Format
c20 = {
    "slug": "multi-format",
    "title": "3.4 多模态与格式处理",
    "description": "PDF/Word/Excel/图片/音频/视频：非结构化数据如何喂给AI",
    "category": "llm", "phase": "C", "order": 20,
    "sections": [
        {"type": "text", "title": "为什么需要多模态处理？", "content": "<p><b>真实世界的数据不只有文本。</b>PDF合同、Excel报表、PPT演示、产品图片、客服录音、监控视频——企业80%的数据是非结构化的。AI如果不能处理这些数据，就无法真正融入工作流。</p><p><b>多模态AI的目标：</b>让模型能同时理解文本、图像、音频、视频，并在它们之间建立关联。例如：\u201C这张图表显示Q3销售额下降，请分析原因并给出建议\u201D——模型需要同时理解图表（图像）和文字指令（文本）。</p><p><b>常见格式与处理方法：</b></p><table border=\"1\"><tr><th>格式</th><th>挑战</th><th>处理方法</th><th>工具</th></tr><tr><td>PDF</td><td>复杂排版、表格、图片混合</td><td>OCR + 版面分析 + 结构化提取</td><td>PyMuPDF, pdfplumber, Marker</td></tr><tr><td>Word</td><td>样式复杂、修订记录、批注</td><td>提取纯文本 + 保留标题层级</td><td>python-docx, mammoth</td></tr><tr><td>Excel</td><td>多sheet、公式、图表</td><td>转CSV/JSON + 保留公式</td><td>pandas, openpyxl</td></tr><tr><td>图片</td><td>分辨率、格式多样、内容复杂</td><td>OCR + 视觉理解模型</td><td>PaddleOCR, GPT-4V</td></tr><tr><td>音频</td><td>方言、噪音、多说话人</td><td>语音识别(ASR) + 说话人分离</td><td>Whisper, FunASR</td></tr><tr><td>视频</td><td>时序信息、关键帧、字幕</td><td>抽帧 + 关键帧理解 + ASR</td><td>ffmpeg, Video-LLaMA</td></tr></table>"},
        {"type": "code", "title": "代码实战：PDF解析与结构化", "content": "<p>PDF是最难处理的格式之一。我们用多种方法解析PDF。</p><pre># 方法1: PyMuPDF (fitz) - 适合文本为主的PDF\nimport fitz  # PyMuPDF\n\ndef extract_text_pymupdf(pdf_path):\n    doc = fitz.open(pdf_path)\n    text = \"\"\"\n    for page in doc:\n        text += page.get_text() + \"\\n\\n\"\n    return text\n\n# 方法2: pdfplumber - 适合表格\nimport pdfplumber\n\ndef extract_tables(pdf_path):\n    tables = []\n    with pdfplumber.open(pdf_path) as pdf:\n        for page in pdf.pages:\n            page_tables = page.extract_tables()\n            tables.extend(page_tables)\n    return tables\n\n# 方法3: Marker - 高质量的PDF转Markdown\n# pip install marker-pdf\nfrom marker.converters.pdf import PdfConverter\nfrom marker.models import create_model_dict\n\nconverter = PdfConverter(create_model_dict())\ndoc = converter(pdf_path)\nmarkdown = doc.rendered\n\n# 表格转DataFrame\nimport pandas as pd\nfor table in tables:\n    df = pd.DataFrame(table[1:], columns=table[0])\n    print(df.head())\u003c/pre><p><b>解析策略选择：</b></p><ul><li><b>纯文本PDF：</b>PyMuPDF（快，简单）</li><li><b>表格多的PDF：</b>pdfplumber（保留表格结构）</li><li><b>复杂排版PDF：</b>Marker（保留标题层级、列表、公式）</li><li><b>扫描版PDF：</b>OCR（PaddleOCR, Tesseract）</li></ul><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>OCR语言</td><td>识别的语言</td><td>chi_sim+eng</td><td>漏设→识别失败</td></tr><tr><td>DPI</td><td>扫描分辨率</td><td>300</td><td>太低→识别差；太高→慢</td></tr><tr><td>chunk_size</td><td>分块大小</td><td>500~1000字符</td><td>太大→丢失粒度；太小→上下文断裂</td></tr></table>"},
        {"type": "code", "title": "代码实战：图片理解与OCR", "content": "<p>让AI看懂图片和提取文字。</p><pre># 方法1: OCR提取文字\nfrom paddleocr import PaddleOCR\n\nocr = PaddleOCR(use_angle_cls=True, lang='ch')  # 中文识别\nresult = ocr.ocr('invoice.jpg', cls=True)\n\nfor line in result[0]:\n    text, confidence = line[1]\n    print(f\"{text} (置信度: {confidence:.2f})\")\n\n# 方法2: GPT-4V理解图片内容\nfrom openai import OpenAI\nclient = OpenAI()\n\nresponse = client.chat.completions.create(\n    model=\"gpt-4o\",\n    messages=[\n        {\"role\": \"user\", \"content\": [\n            {\"type\": \"text\", \"text\": \"这张发票的总金额是多少？\"},\n            {\"type\": \"image_url\", \"image_url\": {\"url\": \"data:image/jpeg;base64,...\"}}\n        ]}\n    ]\n)\nprint(response.choices[0].message.content)\n\n# 方法3: 本地多模态模型 (LLaVA)\nfrom llava.model.builder import load_pretrained_model\nfrom llava.mm_utils import get_model_name_from_path\n\nmodel_path = \"liuhaotian/llava-v1.5-7b\"\ntokenizer, model, image_processor, context_len = load_pretrained_model(\n    model_path=model_path,\n    model_base=None,\n    model_name=get_model_name_from_path(model_path)\n)\n# 然后处理图片和文本...\u003c/pre><p><b>OCR vs 视觉理解：</b></p><ul><li><b>OCR：</b>只提取文字。快、便宜、精确。适合发票、合同、证件。</li><li><b>视觉理解（GPT-4V）：</b>理解图片内容+提取文字。慢、贵、更全面。适合图表分析、场景理解。</li><li><b>本地模型（LLaVA）：</b>隐私好、无API费用。但精度和速度不如GPT-4V。</li></ul>"},
        {"type": "example", "title": "例子：构建文档处理Pipeline", "content": "<p><b>场景：构建一个企业知识库，支持PDF/Word/Excel/图片上传。</b></p><p><b>Pipeline设计：</b></p><pre>上传文件 → 格式检测 → 解析 → 结构化 → Embedding → 存入向量库\n\n1. 格式检测：根据文件扩展名和MIME类型判断\n   .pdf → PDF解析器\n   .docx → Word解析器\n   .xlsx → Excel解析器\n   .jpg/.png → 图片解析器\n\n2. 解析：\n   PDF: Marker → Markdown\n   Word: python-docx → 纯文本 + 标题层级\n   Excel: pandas → CSV/JSON\n   图片: PaddleOCR → 文字 + GPT-4V → 图片描述\n\n3. 结构化：\n   提取标题、段落、表格、图片说明\n   为每段生成摘要\n\n4. Embedding：\n   文本用text-embedding-3-small\n   图片描述也用文本Embedding\n\n5. 存入向量库：\n   Chroma / Milvus / Pinecone\n\n6. 检索增强：\n   用户提问 → 检索相关文档片段 → LLM回答\u003c/pre><p><b>性能指标：</b></p><table border=\"1\"><tr><th>指标</th><th>目标</th><th>优化方法</th></tr><tr><td>解析准确率</td><td>>95%</td><td>多解析器对比，选最优结果</td></tr><tr><td>处理速度</td><td><1秒/页</td><td>并行处理、缓存、预处理</td></tr><tr><td>存储成本</td><td>低</td><td>Embedding压缩、去重</td></tr><tr><td>检索准确率</td><td>>90%</td><td>混合检索、重排序</td></tr></table>"},
        {"type": "exercise", "title": "练习：多模态处理", "content": "<p><b>Q1：</b>为什么PDF是最难处理的格式之一？解析扫描版PDF和文本版PDF有什么区别？</p><p><b>Q2：</b>OCR和视觉理解模型（如GPT-4V）有什么区别？什么时候用OCR，什么时候用视觉理解？</p><p><b>Q3：</b>处理Excel文件时，如何保留公式和多个sheet的关系？</p><p><b>Q4：</b>为什么需要把非结构化数据转换成结构化数据（如Markdown、JSON）再存入向量库？</p><p><b>Q5：</b>设计一个处理医疗报告（PDF+图片）的Pipeline。需要考虑哪些特殊因素？</p>", "answer": "<p><b>A1：</b>PDF是固定版式格式，不像Word有结构化标记。解析扫描版PDF需要OCR（先识别文字），解析文本版PDF直接提取文字。扫描版更慢、更贵、准确率更低。</p><p><b>A2：</b>OCR只提取文字，快、便宜、精确。视觉理解模型能理解图片内容（如识别图表趋势、场景描述），慢、贵、更全面。发票、合同用OCR；图表分析、场景理解用视觉模型。</p><p><b>A3：</b>用openpyxl读取Excel时，可以保存公式字符串（非计算结果），保留sheet名称和关系。需要计算时，可用pandas读取计算后的值，或xlwings调用Excel引擎计算。</p><p><b>A4：</b>非结构化数据（如PDF混合格式）无法直接Embedding。转换成结构化数据后，可以：1.统一格式便于检索；2.保留标题层级便于上下文；3.提取关键信息（表格、公式）便于理解；4.去重和分块。</p><p><b>A5：</b>特殊因素：1.隐私合规（HIPAA等，数据脱敏）；2.医学术语识别（专业OCR模型）；3.手写文字（医生手写处方）；4.图片标注（X光、CT需要专业模型分析）；5.结构化提取（提取诊断、用药、剂量等关键字段）；6.审计追踪（谁访问了什么数据）。</p>"}
    ]
}
save(c20, 'course-20.json')

# Course 21: Integration Guide
c21 = {
    "slug": "integration-guide",
    "title": "3.5 工程整合指南",
    "description": "从原型到生产：API设计/缓存/监控/日志/测试/部署",
    "category": "llm", "phase": "C", "order": 21,
    "sections": [
        {"type": "text", "title": "从原型到生产的鸿沟", "content": "<p><b>写个Demo容易，上线生产难。</b>原型可能只需要100行代码，但生产系统需要考虑：高并发、容错、监控、安全、成本、可维护性。</p><p><b>原型 vs 生产的核心差异：</b></p><table border=\"1\"><tr><th>维度</th><th>原型</th><th>生产</th></tr><tr><td>并发</td><td>1个用户</td><td>1000+并发</td></tr><tr><td>容错</td><td>出错就报错</td><td>自动重试、降级、熔断</td></tr><tr><td>监控</td><td>print调试</td><td>日志、指标、告警、追踪</td></tr><tr><td>安全</td><td>硬编码API key</td><td>密钥管理、权限控制、审计</td></tr><tr><td>成本</td><td>无所谓</td><td>预算控制、用量限制</td></tr><tr><td>部署</td><td>本地运行</td><td>CI/CD、容器化、自动扩缩容</td></tr></table><p><b>生产级AI系统的核心组件：</b></p><ol><li><b>API层：</b>RESTful API或gRPC，统一入口</li><li><b>缓存层：</b>Redis缓存常见查询结果</li><li><b>队列层：</b>RabbitMQ/Kafka处理异步任务</li><li><b>模型服务：</b>GPU集群或云API</li><li><b>监控层：</b>Prometheus + Grafana</li><li><b>日志层：</b>ELK Stack (Elasticsearch + Logstash + Kibana)</li></ol>"},
        {"type": "text", "title": "API设计与缓存策略", "content": "<p><b>API设计原则：</b></p><p><b>1. 幂等性：</b>同一请求多次调用，结果相同。POST/PUT应该是幂等的。实现：每个请求带唯一ID，服务端去重。</p><p><b>2. 版本控制：</b>/v1/chat, /v2/chat。避免破坏性更新影响现有用户。</p><p><b>3. 限流：</b>Token Bucket或Leaky Bucket算法。防止单个用户耗尽资源。</p><p><b>4. 超时与重试：</b>设置合理的超时时间（如30秒）。失败时指数退避重试：1s, 2s, 4s, 8s。</p><p><b>缓存策略：</b></p><pre>1. 结果缓存：相同输入直接返回缓存结果\n   适用：常见问题、固定知识查询\n   TTL: 1小时~1天\n\n2. 向量缓存：缓存Embedding结果\n   适用：重复查询的文本\n   节省：Embedding API调用费用\n\n3. 会话缓存：缓存对话历史\n   适用：多轮对话\n   避免：每次请求重复发送历史\n\n4. 多级缓存：\n   L1: 本地内存 (Redis) - 10ms\n   L2: 分布式缓存 (Redis Cluster) - 50ms\n   L3: 数据库 - 200ms\u003c/pre><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>缓存TTL</td><td>缓存过期时间</td><td>1h~24h</td><td>太长→数据陈旧；太短→缓存失效</td></tr><tr><td>限流QPS</td><td>每秒最大请求数</td><td>10~1000</td><td>太高→资源耗尽；太低→用户体验差</td></tr><tr><td>超时时间</td><td>最大等待时间</td><td>30s~60s</td><td>太长→资源占用；太短→正常请求失败</td></tr></table>"},
        {"type": "code", "title": "代码实战：生产级API服务", "content": "<p>用FastAPI构建一个生产级AI API服务。</p><pre># 安装: pip install fastapi uvicorn redis\nfrom fastapi import FastAPI, HTTPException, Depends\nfrom fastapi.middleware.cors import CORSMiddleware\nfrom pydantic import BaseModel\nimport redis, hashlib, json, time\nfrom functools import wraps\n\napp = FastAPI()\n\n# CORS\napp.add_middleware(\n    CORSMiddleware,\n    allow_origins=[\"*\"],\n    allow_methods=[\"*\"],\n    allow_headers=[\"*\"],\n)\n\n# Redis缓存\nredis_client = redis.Redis(host='localhost', port=6379, db=0)\n\n# 请求模型\nclass ChatRequest(BaseModel):\n    message: str\n    session_id: str = None\n    temperature: float = 0.7\n\n# 缓存装饰器\ndef cache_response(ttl=3600):\n    def decorator(func):\n        @wraps(func)\n        async def wrapper(*args, **kwargs):\n            # 生成缓存key\n            cache_key = f\"cache:{func.__name__}:{hashlib.md5(str(args).encode()).hexdigest()}\"\n            \n            # 查缓存\n            cached = redis_client.get(cache_key)\n            if cached:\n                return json.loads(cached)\n            \n            # 执行函数\n            result = await func(*args, **kwargs)\n            \n            # 存入缓存\n            redis_client.setex(cache_key, ttl, json.dumps(result))\n            return result\n        return wrapper\n    return decorator\n\n# 限流装饰器\ndef rate_limit(max_requests=10, window=60):\n    def decorator(func):\n        @wraps(func)\n        async def wrapper(*args, **kwargs):\n            # 简单限流实现\n            return await func(*args, **kwargs)\n        return wrapper\n    return decorator\n\n@app.post(\"/api/v1/chat\")\n@cache_response(ttl=1800)\n@rate_limit(max_requests=100, window=60)\nasync def chat(request: ChatRequest):\n    try:\n        # 调用LLM API\n        response = await call_llm_api(\n            message=request.message,\n            temperature=request.temperature\n        )\n        \n        return {\n            \"status\": \"success\",\n            \"data\": response,\n            \"cached\": False,\n            \"timestamp\": time.time()\n        }\n    except Exception as e:\n        # 错误处理\n        raise HTTPException(status_code=500, detail=str(e))\n\n# 健康检查\n@app.get(\"/health\")\nasync def health():\n    return {\"status\": \"healthy\", \"version\": \"1.0.0\"}\n\nif __name__ == \"__main__\":\n    import uvicorn\n    uvicorn.run(app, host=\"0.0.0.0\", port=8000)\u003c/pre><p><b>生产部署：</b></p><pre># Dockerfile\nFROM python:3.11-slim\nWORKDIR /app\nCOPY requirements.txt .\nRUN pip install -r requirements.txt\nCOPY . .\nCMD [\"uvicorn\", \"main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\", \"--workers\", \"4\"]\n\n# docker-compose.yml\nversion: '3'\nservices:\n  api:\n    build: .\n    ports:\n      - \"8000:8000\"\n    environment:\n      - REDIS_URL=redis://redis:6379\n    depends_on:\n      - redis\n  redis:\n    image: redis:alpine\n    ports:\n      - \"6379:6379\"\u003c/pre>"},
        {"type": "exercise", "title": "练习：工程整合", "content": "<p><b>Q1：</b>为什么生产系统需要幂等性？如何实现请求的幂等性？</p><p><b>Q2：</b>缓存的TTL设置需要考虑哪些因素？如果TTL=1秒和TTL=1天分别有什么问题？</p><p><b>Q3：</b>限流的Token Bucket和Leaky Bucket算法有什么区别？</p><p><b>Q4：</b>为什么生产API需要版本控制（/v1/, /v2/）？如果不做版本控制会怎样？</p><p><b>Q5：</b>设计一个AI客服系统的架构。需要哪些组件？如何处理高并发？</p>", "answer": "<p><b>A1：</b>幂等性防止重复操作。网络超时后客户端重试，如果没有幂等性，同一个请求可能被执行多次（如扣款两次）。实现：每个请求带唯一ID，服务端记录已处理的ID，重复请求直接返回之前的结果。</p><p><b>A2：</b>TTL需要考虑数据更新频率和用户期望。TTL=1秒：缓存几乎失效，每次都要重新计算，缓存失去意义。TTL=1天：数据可能陈旧，用户看到过期信息。平衡：频繁变化的数据TTL短（分钟级），稳定数据TTL长（天级）。</p><p><b>A3：</b>Token Bucket：桶里有固定数量的token，每个请求消耗一个token，token以固定速率补充。允许突发流量（桶里有token就能处理）。Leaky Bucket：请求进入桶，以固定速率流出。平滑流量，不允许突发。Token Bucket更灵活，Leaky Bucket更严格。</p><p><b>A4：</b>版本控制允许平滑升级。不做版本控制：修改API后，旧客户端可能崩溃。例如：把字段name改成full_name，旧客户端找不到name字段就报错。版本控制让新旧客户端共存。</p><p><b>A5：</b>组件：API网关（限流、认证）、AI服务（LLM + RAG知识库）、对话管理（维护会话状态）、缓存层（Redis）、消息队列（异步任务）、监控告警（Prometheus）、日志系统（ELK）。高并发：水平扩展（多实例负载均衡）、缓存热点问题、异步处理非实时任务、数据库读写分离。</p>"}
    ]
}
save(c21, 'course-21.json')

# Course 22: MLOps
c22 = {
    "slug": "mlops",
    "title": "3.6 MLOps",
    "description": "模型版本管理/CI-CD/监控/A-B测试：AI系统的持续运维",
    "category": "llm", "phase": "C", "order": 22,
    "sections": [
        {"type": "text", "title": "什么是MLOps？——DevOps的AI版本", "content": "<p><b>MLOps = Machine Learning + Operations。</b>把DevOps的最佳实践应用到机器学习系统。包括：模型开发、训练、部署、监控、更新的全生命周期管理。</p><p><b>为什么MLOps比DevOps更难？</b></p><ul><li><b>模型是代码+数据：</b>传统软件只需要版本控制代码，ML还需要版本控制数据、超参数、模型权重</li><li><b>模型会退化：</b>数据分布变化（概念漂移）导致模型性能下降，需要持续监控</li><li><b>实验管理：</b>ML需要大量实验（不同超参数、不同数据），需要追踪每次实验</li><li><b>可复现性：</b>同样的代码+数据+超参数，必须得到同样的结果</li></ul><p><b>MLOps生命周期：</b></p><pre>1. 数据准备：收集、清洗、标注、版本化\n2. 实验：训练多个模型，比较性能\n3. 模型注册：把最佳模型注册到模型仓库\n4. 部署：把模型部署到生产环境\n5. 监控：监控模型性能、数据漂移、延迟\n6. 再训练：性能下降时，用新数据重新训练\n7. A/B测试：新模型 vs 旧模型，逐步切换\u003c/pre><p><b>MLOps工具链：</b></p><table border=\"1\"><tr><th>功能</th><th>工具</th></tr><tr><td>实验追踪</td><td>MLflow, Weights & Biases, TensorBoard</td></tr><tr><td>模型注册</td><td>MLflow Model Registry, DVC</td></tr><tr><td>工作流编排</td><td>Airflow, Kubeflow, Prefect</td></tr><tr><td>特征存储</td><td>Feast, Tecton</td></tr><tr><td>监控</td><td>Evidently, WhyLabs, Arize</td></tr></table>"},
        {"type": "code", "title": "代码实战：MLflow实验追踪", "content": "<p>用MLflow追踪实验和模型版本。</p><pre># 安装: pip install mlflow\nimport mlflow\nimport mlflow.sklearn\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score\n\n# 设置追踪服务器\nmlflow.set_tracking_uri(\"http://localhost:5000\")\nmlflow.set_experiment(\"customer-churn-prediction\")\n\n# 开始实验\nwith mlflow.start_run(run_name=\"rf_model_v1\"):\n    # 记录参数\n    params = {\n        \"n_estimators\": 100,\n        \"max_depth\": 10,\n        \"min_samples_split\": 5\n    }\n    mlflow.log_params(params)\n    \n    # 训练模型\n    model = RandomForestClassifier(**params)\n    model.fit(X_train, y_train)\n    \n    # 评估\n    y_pred = model.predict(X_test)\n    accuracy = accuracy_score(y_test, y_pred)\n    \n    # 记录指标\n    mlflow.log_metric(\"accuracy\", accuracy)\n    mlflow.log_metric(\"precision\", precision_score(y_test, y_pred))\n    mlflow.log_metric(\"recall\", recall_score(y_test, y_pred))\n    \n    # 记录模型\n    mlflow.sklearn.log_model(model, \"model\")\n    \n    # 记录特征重要性图\n    import matplotlib.pyplot as plt\n    feat_importances = pd.Series(model.feature_importances_, index=feature_names)\n    feat_importances.nlargest(10).plot(kind='barh')\n    plt.savefig(\"feature_importance.png\")\n    mlflow.log_artifact(\"feature_importance.png\")\n\nprint(f\"Experiment logged! Accuracy: {accuracy:.4f}\")\n\n# 查看实验结果\n# 打开 http://localhost:5000 查看所有实验\u003c/pre><p><b>MLflow核心概念：</b></p><ul><li><b>Experiment（实验）：</b>一组相关的Run。如\u201C客户流失预测\u201D。</li><li><b>Run（运行）：</b>一次具体的训练。包含参数、指标、模型、Artifact。</li><li><b>Artifact（产物）：</b>训练过程中产生的文件，如图表、数据集、模型。</li><li><b>Model Registry（模型注册表）：</b>管理模型的生命周期：Staging → Production → Archived。</li></ul>"},
        {"type": "text", "title": "模型监控与A/B测试", "content": "<p><b>为什么需要监控模型？</b>模型上线后，真实数据分布可能与训练数据不同。例如：训练时客户主要是年轻人，上线后老年人增多，模型可能不再准确。</p><p><b>监控维度：</b></p><table border=\"1\"><tr><th>监控项</th><th>指标</th><th>告警阈值</th></tr><tr><td>模型性能</td><td>准确率、F1、AUC</td><td>下降>5%</td></tr><tr><td>数据漂移</td><td>特征分布KL散度、PSI</td><td>PSI>0.2</td></tr><tr><td>概念漂移</td><td>标签分布变化</td><td>显著变化</td></tr><tr><td>延迟</td><td>P50/P95/P99响应时间</td><td>P99>500ms</td></tr><tr><td>吞吐量</td><td>QPS</td><td>低于目标</td></tr><tr><td>错误率</td><td>5xx错误比例</td><td>>1%</td></tr></table><p><b>A/B测试：</b>新模型（B）和旧模型（A）同时运行，逐步把流量切给B。</p><pre>阶段1: A=100%, B=0%   (基线)\n阶段2: A=90%,  B=10%  (小流量验证)\n阶段3: A=70%,  B=30%  (逐步放大)\n阶段4: A=50%,  B=50%  (对照实验)\n阶段5: A=20%,  B=80%  (接近全量)\n阶段6: A=0%,   B=100% (完全切换)\n\n每个阶段监控：\n- 业务指标（转化率、收入）\n- 模型指标（准确率、延迟）\n- 用户反馈（满意度、投诉率）\n\n如果B的性能显著优于A（p<0.05），继续放量。\n如果B的性能显著差于A，回滚到A。\u003c/pre><p><b>参数表：</b></p><table border=\"1\"><tr><th>参数</th><th>含义</th><th>典型值</th><th>太大/太小</th></tr><tr><td>A/B流量比例</td><td>B模型接收的流量比例</td><td>10%~50%</td><td>太高→风险大；太低→统计不显著</td></tr><tr><td>置信水平</td><td>统计显著性</td><td>95% (p<0.05)</td><td>太高→难显著；太低→误判</td></tr><tr><td>监控窗口</td><td>评估周期</td><td>7天~30天</td><td>太短→随机波动；太长→风险暴露</td></tr></table>"},
        {"type": "exercise", "title": "练习：MLOps", "content": "<p><b>Q1：</b>MLOps和DevOps的核心区别是什么？为什么ML需要额外的实验管理？</p><p><b>Q2：</b>什么是数据漂移（Data Drift）和概念漂移（Concept Drift）？举例说明。</p><p><b>Q3：</b>A/B测试中，为什么流量不能一次性切到100%新模型？</p><p><b>Q4：</b>MLflow的Run、Experiment、Artifact分别是什么？</p><p><b>Q5：</b>模型监控中，如果准确率下降但数据漂移指标正常，可能是什么原因？</p>", "answer": "<p><b>A1：</b>MLOps需要管理代码+数据+模型+超参数。DevOps只管理代码。ML需要实验管理是因为：1.超参数组合多，需要追踪每次实验；2.数据版本影响模型性能；3.需要比较不同实验选择最佳模型；4.可复现性要求。</p><p><b>A2：</b>数据漂移：输入特征的分布变化。例：训练时用户年龄20-30岁，上线后40-50岁用户增多。概念漂移：输入和输出关系变化。例：疫情期间训练的销售预测模型，疫情后消费习惯改变，模型失效。</p><p><b>A3：</b>一次性切换风险太大。如果新模型有bug或在某些场景表现差，100%流量会导致严重事故。逐步放量可以及时发现问题并回滚。通常从5%~10%开始。</p><p><b>A4：</b>Run：一次具体的训练执行，包含参数、指标、时间戳。Experiment：一组相关的Run（如同一个任务的不同实验）。Artifact：训练产生的文件（模型、图表、数据集）。</p><p><b>A5：</b>可能原因：1.标签质量问题（标注错误增多）；2.模型bug（代码更新引入）；3.特定子群体性能下降（整体指标掩盖了局部问题）；4.对抗样本或异常输入；5.上游数据预处理变化。</p>"}
    ]
}
save(c22, 'course-22.json')

print('\nDone with courses 20-22!')
