import type { Character } from "./types";

const charactersData: Character[] = [
  {
    id: "lady-gaga",
    name: "雷迪嘎嘎",
    name_en: "Lady Gaga",
    species: "乌鸦",
    species_en: "Raven",
    role: "父亲 · 主角",
    role_en: "Father · Protagonist",
    key_features: "额头灰色伤疤，黑灰羽毛，威严沉稳",
    description: "一只经历过故事的乌鸦。额头上的伤疤诉说着过往，沉稳的目光中藏着智慧。他是这个世界的中心，所有故事的主角。",
    personality: "严肃沉稳，不善言辞但行动力强。外表看似冷酷，内心却温柔细腻。为了保护家人可以付出一切。",
    color: "from-gray-800 to-slate-700",
    emoji: "🐦‍⬛",
    storyCount: 1840,
  },
  {
    id: "gababa",
    name: "噶巴巴",
    name_en: "Gababa",
    species: "乌鸦",
    species_en: "Raven",
    role: "儿子 · 成长主角",
    role_en: "Son · Growth Hero",
    key_features: "小型圆眼，左翅尖缺口，胸前灰色绒毛",
    description: "雷迪嘎嘎的儿子，一只充满好奇心的小乌鸦。他正在学习这个世界的一切，每一天都是新的冒险。",
    personality: "活泼好动，充满好奇心。有时冒失，但心地善良。在冒险中成长为敢于担当的小男子汉。",
    color: "from-blue-800 to-indigo-700",
    emoji: "🐤",
    storyCount: 240,
  },
  {
    id: "gayaya",
    name: "噶丫丫",
    name_en: "Gayaya",
    species: "白乌鸦",
    species_en: "White Raven",
    role: "女儿 · 成长主角",
    role_en: "Daughter · Growth Hero",
    key_features: "全身上下纯白色羽毛，圆眼微垂，性格内向",
    description: "雷迪嘎嘎的女儿，罕见的小白乌鸦。她温柔细腻，敏感多思，拥有一颗纯净如她羽毛的心。",
    personality: "内向害羞，紧张时会不自觉地梳理羽毛。温柔善良，善于观察，有很强的情感感知力。",
    color: "from-purple-800 to-violet-700",
    emoji: "🕊️",
    storyCount: 240,
  },
  {
    id: "chenguang",
    name: "晨光",
    name_en: "Morning Sun",
    species: "白乌鸦",
    species_en: "White Raven",
    role: "妻子 · 思念",
    role_en: "Wife · In Memory",
    key_features: "洁白如雪的羽毛，温柔的眼神",
    description: "雷迪嘎嘎的妻子，噶巴巴和噶丫丫的母亲。虽然已经不在身边，但她的爱与温暖永远守护着这个家。",
    personality: "温柔体贴，善解人意。是这个家的光和温暖，即使在记忆中依然闪耀。",
    color: "from-amber-800 to-yellow-700",
    emoji: "🌅",
    storyCount: 53,
  },
  {
    id: "nainai",
    name: "奶奶",
    name_en: "Grandma",
    species: "乌鸦",
    species_en: "Raven",
    role: "祖母 · 智慧",
    role_en: "Grandmother · Wisdom",
    key_features: "灰白的羽毛，慈祥的眼神",
    description: "雷迪嘎嘎的母亲，家族的长者。她见证了家族的兴衰，拥有数不清的故事和经验。",
    personality: "慈祥和蔼，睿智通达。喜欢给孩子们讲故事，是家族的历史传承者。",
    color: "from-gray-500 to-stone-600",
    emoji: "👵",
    storyCount: 50,
  },
  {
    id: "san-zhi",
    name: "伞志",
    name_en: "San Zhi",
    species: "松鼠",
    species_en: "Squirrel",
    role: "朋友 · 智囊",
    role_en: "Friend · Brain",
    key_features: "蓬松大尾巴，圆眼睛，总是背着一个松果书包",
    description: "一只机灵的松鼠，雷迪嘎嘎最可靠的朋友。当你需要出主意的时候，找伞志准没错。",
    personality: "聪明机灵，善于思考。有些唠叨但每次都能给出好建议。是团队里的智多星。",
    color: "from-emerald-800 to-teal-700",
    emoji: "🐿️",
    storyCount: 100,
  },
  {
    id: "bai-youbai",
    name: "白攸白",
    name_en: "Bai Youbai",
    species: "兔子",
    species_en: "Rabbit",
    role: "朋友 · 行动派",
    role_en: "Friend · Doer",
    key_features: "纯白色皮毛，长耳朵，红色眼睛",
    description: "勇敢又冲动的兔子朋友，总是第一个冲出去行动。虽然偶尔鲁莽，但关键时刻从不掉链子。",
    personality: "开朗活泼，行动力超强。想到就做，不拖泥带水。偶尔冲动但心地纯良。",
    color: "from-rose-800 to-pink-700",
    emoji: "🐰",
    storyCount: 80,
  },
  {
    id: "zhen-gugu",
    name: "真咕咕",
    name_en: "Zhen Gugu",
    species: "猫头鹰",
    species_en: "Owl",
    role: "老师 · 智者",
    role_en: "Teacher · Wise One",
    key_features: "大眼睛，棕褐色羽毛，戴着小小的读书眼镜",
    description: "森林学校的老师，最有学识的长者。他教会了所有小朋友读书写字。",
    personality: "博学多识，耐心温和。喜欢在课堂上讲有趣的故事来教授知识。",
    color: "from-amber-900 to-orange-800",
    emoji: "🦉",
    storyCount: 70,
  },
  {
    id: "ding-lingling",
    name: "丁凌凌",
    name_en: "Ding Lingling",
    species: "鹰",
    species_en: "Eagle",
    role: "亦敌亦友",
    role_en: "Rival & Friend",
    key_features: "金棕色羽毛，锋利的眼神，翅膀张开时威风凛凛",
    description: "同样生活在天空的竞争者。他和雷迪嘎嘎既是竞争对手，也是互相尊重的朋友。",
    personality: "正直高傲，竞争心强但光明磊落。从不耍手段，靠实力说话。",
    color: "from-cyan-800 to-sky-700",
    emoji: "🦅",
    storyCount: 40,
  },
  {
    id: "ding-gang-chongchong",
    name: "丁刚冲冲",
    name_en: "Ding Gang Chongchong",
    species: "鹰",
    species_en: "Eagle",
    role: "反派 · 冲突",
    role_en: "Bully · Antagonist",
    key_features: "深色羽毛，体型硕大，眼神凶悍",
    description: "森林里的麻烦制造者。他总是想证明自己最强，但用的方法总是不太对。",
    personality: "暴躁好斗，喜欢欺负人。但内心深处也有柔软的一面，只是从不表现出来。",
    color: "from-red-900 to-rose-800",
    emoji: "🦅",
    storyCount: 30,
  },
  {
    id: "hua-lala",
    name: "花拉拉",
    name_en: "Hua Lala",
    species: "鹿",
    species_en: "Deer",
    role: "同学 · 温柔担当",
    role_en: "Classmate · Gentle Soul",
    key_features: "棕色皮毛上的白色斑点，温润的大眼睛",
    description: "森林学校里最温柔的同学。她总是默默帮助别人，从不求回报。",
    personality: "温柔体贴，善解人意。是大家心中最暖心的存在。",
    color: "from-amber-700 to-yellow-600",
    emoji: "🦌",
    storyCount: 60,
  },
  {
    id: "tu-lulu",
    name: "土噜噜",
    name_en: "Tu Lulu",
    species: "刺猬",
    species_en: "Hedgehog",
    role: "同学 · 搞笑担当",
    role_en: "Classmate · Comic Relief",
    key_features: "圆滚滚的身体，背上竖满尖刺，总是摔跤",
    description: "森林学校里最小但最有趣的家伙。他总是在跌跌撞撞中把事情做成。",
    personality: "笨拙但乐观，做什么都容易搞砸但从不放弃。是大家的开心果。",
    color: "from-brown-800 to-stone-700",
    emoji: "🦔",
    storyCount: 60,
  },
];

export default charactersData;
